# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (voltage IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (voltage IS cluster2) THEN (OUTPUT IS fun2)"
FS.add_rules([RULE1, RULE2])

FS.set_output_function('fun1', '4.724371+0.043687*voltage')
FS.set_output_function('fun2', '4.726978+-0.01212*voltage')

FS_1 = FuzzySet(function=Gaussian_MF(6.989864, 2.040304), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(2.788740, 2.154338), term='cluster2')
MF_voltage = LinguisticVariable([FS_1, FS_2], concept='voltage')
FS.add_linguistic_variable('voltage', MF_voltage)


# end of automatically generated code #