# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (voltage IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (voltage IS cluster2) THEN (OUTPUT IS fun2)"
FS.add_rules([RULE1, RULE2])

FS.set_output_function('fun1', '0.547156+0.043972*voltage')
FS.set_output_function('fun2', '0.487026+-0.011522*voltage')

FS_1 = FuzzySet(function=Gaussian_MF(1.208867, 0.685764), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(-0.270671, 0.752484), term='cluster2')
MF_voltage = LinguisticVariable([FS_1, FS_2], concept='voltage')
FS.add_linguistic_variable('voltage', MF_voltage)


# end of automatically generated code #